language: common-lisp

sudo: false

os:
  - linux
  - osx

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=tests # for Prove or Rove
    - ROSWELL_BRANCH=master  # use Roswell master for latest updates
  matrix:
    - LISP=sbcl
    - LISP=ccl COVERAGE=1
    # - LISP=abcl
    # - LISP=clisp
    # - LISP=cmucl
    # - LISP=ecl

matrix:
  fast_finish: true
  allow_failures:
    - env: LISP=ccl COVERAGE=1
    - env: LISP=clisp
    - env: LISP=abcl
    - env: LISP=alisp
    - env: LISP=cmucl
    - env: LISP=ecl

addons:
  apt:
    packages:
      # - libc6-i386     # needed for some implementations
      # - openjdk-8-jre  # needed for ABCL

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - git clone --depth=1 git://github.com/soemraws/parse-float.git ~/common-lisp/parse-float
  - ros install fukamachi/rove  # Use Rove master for latest updates
  - if [ "$COVERAGE" = "1" ]; then ros install fukamachi/cl-coveralls; fi

script:
  - rove cl-kraken.asd

after_script:
  - if [ "$COVERAGE" = "1" ]; then
      coveralls report/;
    fi
